### ISSUE TITLE
完成前端登录模块

### ISSUE THREAD

**Issue by StellaSong12** [sysu-SAAD-project/front-end#1]
1.检查前端是否保存token
2.若未保存，完成用户微信登录
3.将登录返回的code发送到后端
4.保存从后端返回的token

**Comment by starthemoon** [comment]
前端模块：add
1. currentUserLogin：当前用户登录微信服务端，并将返回的code发送给本服务端，最后将本服务端返回的token进行本地存储
2. checkWhetherTokenExists：检查本地缓存是否有token，如果有发送则给服务端，否则进行当前用户登录
3. saveTokenOfCurrentUser：本地存储本服务端返回的token
所有的调用均在app的onLaunch里，目前并不清楚调用次数
