### ISSUE TITLE
几个前端的改进点

### ISSUE THREAD

**Issue by starthemoon** [sysu-SAAD-project/front-end#9]
1. posterWall里标题栏应浮动
2.  “我的”→“我报名的”里的活动详情应该不现实“报名该活动”按钮

**Comment by starthemoon** [comment]
已改善，请领导过目

**Comment by StellaSong12** [comment]
实现1
实现2：“我的”→“我报名的”显示“您已报名”，但点击仍可添加报名，方便为他人继续报名该活动
